name: static-analyzation
on: [push]

jobs:
  build:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.2
